"""Adding username column password column

Revision ID: 2dec9a55af53
Revises: 367cf00e7954
Create Date: 2023-01-11 16:18:51.723049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dec9a55af53'
down_revision = '367cf00e7954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=64), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
