"""Adding sald and created_at columns

Revision ID: 304aa6eab6e0
Revises: 2dec9a55af53
Create Date: 2023-01-11 16:21:30.903971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304aa6eab6e0'
down_revision = '2dec9a55af53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
