"""Adding username column

Revision ID: 367cf00e7954
Revises: 
Create Date: 2023-01-11 16:12:29.103833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367cf00e7954'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=128), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
