"""Adding some columns

Revision ID: 6110ea615eaa
Revises: b171e7074a6e
Create Date: 2023-01-11 16:31:05.193306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6110ea615eaa'
down_revision = 'b171e7074a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
