"""Delete extra column

Revision ID: 7951dfc2a6e2
Revises: ba1922eac7a1
Create Date: 2023-01-10 22:09:38.225881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7951dfc2a6e2'
down_revision = 'ba1922eac7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('extra')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
