"""Adding extra column to User table

Revision ID: ba1922eac7a1
Revises: 24afe87fb61c
Create Date: 2023-01-10 22:03:17.106669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1922eac7a1'
down_revision = '24afe87fb61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productotemp2')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('extra')

    op.create_table('productotemp2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('precio', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('foto', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('tipo_foto', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comentario2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='productotemp2_pkey')
    )
    # ### end Alembic commands ###
